// tictactoe-reactjs/src/components/app/App.tsx
import React from 'react';
import logo from '../../assets/logo.svg';
import './App.css';
import { TicTacToe } from '../tic-tac-toe/ticTacToe'

export default class App extends React.Component {
  render(){
    return (
      <div className="App">
        <TicTacToe />
        <img src={logo} className="App-logo" alt="logo" />
      </div>
    );
  }
}

// TicTacToe-VueJS/src/App.vue
<template>
	<div id="app">
		<img alt="Vue logo" src="./assets/logo.png" />
		<!-- <HelloWorld msg="Welcome to Your Vue.js App"/> -->
		<tic-tac-toe />
	</div>
</template>

<script>
// import HelloWorld from './components/HelloWorld.vue'
import TicTacToe from './components/TicTacToe.vue';
export default {
	name: 'App',
	components: {
		// HelloWorld
		'tic-tac-toe': TicTacToe,
	},
};
</script>

<style>
#app {
	font-family: Avenir, Helvetica, Arial, sans-serif;
	-webkit-font-smoothing: antialiased;
	-moz-osx-font-smoothing: grayscale;
	text-align: center;
	color: #2c3e50;
	margin-top: 60px;
}
</style>
